### ISSUE TITLE
Beatsaber closing after level complete

### ISSUE THREAD

**Issue by sharkdiver99** [Metalit/QuestBeatSaviourData#1]
I tracked down my "beat saber crashing on song completion issue" to the BeatSaviourData Mod. After completion the screen goes black, three dots appear an the game closes. Interestingly if I fail a song the crash dosen't occur and the stats are shown correctly. 

I am using BS version 1.17.1, BMBF 1.15.0  and a ton of mods which I seperatly activated and deactivated to find the cause.
It'd be very nice if you could look into this issue. :)

**Comment by Metalit** [comment]
This was a strange and mysterious compatibility issue with qosmetics and replay that I still don't understand the cause of, but with the new update and reworking of the internal mechanics of both this and the upcoming qosmetics rewrite, this issue will hopefully be taken care of. For now, with qosmetics unreleased, it definitely won't be occurring.
Sorry I couldn't find a fix for 1.17.1, I spent quite a while trying to figure it out as well before the initial release, but ended up having to simply disclaim it in the discord release post.
