### ISSUE TITLE
Enable mod in Party Mode

### ISSUE THREAD

**Issue by ecl1ps** [Metalit/QuestBeatSaviourData#2]
Hi, great mod, loving it.

I have a feature request. Could you enable it also in the Party Mode, the same way as it is working in singleplayer? 

Thanks!

**Comment by Metalit** [comment]
Added in the new update! Sorry I didn't see this sooner, but thankfully someone else mentioned it to me as well.

**Comment by ecl1ps** [comment]
Great, thank you. I can confirm it is working.
